[DEFAULT]
MQTT_HOST=192.168.0.2
MQTT_PORT=1883
MQTT_USERNAME=
MQTT_PASSWORD=
MQTT_CLIENT_NAME=RS485-002
MQTT_LOOP_DELAY=0.1
LOGFILE_NAME=rs485-activity.log
MQTT_STARTUP_MESSAGE=%(datetimenow)s
MQTT_STARTUP_TOPIC=RS485-002/STATUS/boottime
MQTT_DEVICE_STATUS_REQUEST_TOPIC=RS485-002/CMD/STATUS
MQTT_DEVICE_STATUS_RESPONSE_TOPIC=RS485-002/STATUS/DEVICE_STATUS
MQTT_HEXADECIMAL_CONTROL_TOPIC=RS485-002/CMD/CTRL
MQTT_QOS=1
MQTT_RETAIN=1
RS485_DEVICE=/dev/ttyUSB0
RS485_BAUD_RATE=115200


;Output 31 
[DEV1OUTPUT31]
TYPE=GPIO
GPIO_TYPE=OUTPUT
MODBUS_ADDR=1
MODBUS_IO=31
MQTT_TOPICS={"MQTT_TOPICS": ["RS485-002/CMD/1/31"]}
MQTT_PARSER=STRONOFF
MQTT_PARSER_ARG1=Output
LOG_MESSAGE=Setting Output: %(output)d at Modbus Address: %(address)s to value: %(value)s based upon message: %(message)s on MQTT topic: %(topic)s
MQTT_QOS=1
MQTT_RETAIN=True


[DEV1INPUT1VIRTUAL]
TYPE=VIRTUALINPUT
GPIO_TYPE=VIRTUAL
MODBUS_ADDR=1
MODBUS_IO=0
MQTT_TOPICS={"MQTT_TOPICS":["RS485-002/STATUS/V1/SINGLE","RS485-002/STATUS/V1/DOUBLE","RS485-002/STATUS/V1/TRIPLE","RS485-002/STATUS/V1/QUAD","RS485-002/STATUS/V1/QUIN"],"MQTT_HOLD_TOPICS":["RS485-002/STATUS/V1/HOLD"]}
MQTT_MESSAGE={"ModbusAddress": {MODBUSADDRESS}, "Input": {INPUT}, "State": "{STATE}", "UTCtimestamp": {UTCTIMESTAMP}, "updatedat":"{UPDATEDAT}"}
MQTT_HOLD_MESSAGE={"ModbusAddress": {MODBUSADDRESS}, "Input": {INPUT}, "State": "{STATE}", "UTCtimestamp": {UTCTIMESTAMP}, "updatedat":"{UPDATEDAT}", "holdTime":{HOLDTIME}}
MQTT_QOS=1
MQTT_RETAIN=True
LOG_MESSAGE=Published MQTT Message: %(message)s to topic: %(topic)s

;INPUT 1
[DEV1INPUT1]
TYPE=GPIO
GPIO_TYPE=INPUT
MODBUS_ADDR=1
MODBUS_IO=0
MQTT_TOPICS={"MQTT_TOPICS":["RS485-002/STATUS/1/0"]}
MQTT_MESSAGE={"ModbusAddress": {MODBUSADDRESS}, "Input": {INPUT}, "State": "{STATE}", "UTCtimestamp": {UTCTIMESTAMP}, "updatedat":"{UPDATEDAT}"}
MQTT_QOS=1
MQTT_RETAIN=True
LOG_MESSAGE=Published MQTT Message: %(message)s to topic: %(topic)s


